### ISSUE TITLE
How to find/craft the added items?

### ISSUE THREAD

**Issue by 36desires** [Silvertide7/homebound#3]
Hello there and thanks for this great mod. 
I've recently added this to my dedicated minecraft server and client. I can use the "/homebound info" command in the chat and will receive a response. Unfortunately I have no idea where/how to find the items (mainly in order to verify that the mod is actually working yet). Could you elaborate how the added items are meant to be found/crafted and what exactly needs to be added to the dedicated server files? I've just copied the homebound-1.20.2-1.0.4.jar to the mods folder of the server.

Cheers and thanks a lot - I love the concept of this mod.

Simon

**Comment by Silvertide7** [comment]
Hey Simon! Thanks for the kind words!
The items are crafted from normal vanilla items. The first item you will need to find to get started is 2 amethyst and an ender pearl. This will unlock a recipe in your recipe book for the first item you will need, the homeward shard. This is crafted in a crafting table in a line with [Amethyst Shard, Ender Pearl, Amethyst Shard].

I strongly recommend installing [JEI](https://www.curseforge.com/minecraft/mc-mods/jei) to your mods folder as well. This mod will allow you to look up recipes in the inventory screen. The mod should be working if the command you're running is working for you. Let me know if you need anything else!

**Comment by 36desires** [comment]
Hello Silvertide7, 

thanks for the quick reply and explanation. The mod is indeed working as intended and I've used JEI to double-confirm this. Looking forward to discovering & crafting these teleportation items.
You have a great day & all the best,
Simon
